// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dugvorikvxmjicapftmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1Z3ZvcmlrdnhtamljYXBmdG1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NTA3ODQsImV4cCI6MjA3NzEyNjc4NH0.lLs-KtJ6IJ8jHkFP-GuOl7vTRtYwA4yvY9oTD8Ct8YQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
